{% set name = "sqlalchemy-spanner" %}
{% set version = "1.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/archive/refs/tags/v{{ version }}.zip
  sha256: 858e8a552fb9d753347ccdb599e5b9ea8667b51b578b9eb4a6aee64bba1c5de4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - sqlalchemy >=1.1.13
    - google-cloud-spanner >=3.12.0
    - alembic

test:
  imports:
    - google.cloud.sqlalchemy_spanner
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/googleapis/python-spanner-sqlalchemy
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Spanner dialect for SQLAlchemy

extra:
  recipe-maintainers:
    - xylar
    - hadim
