{% set name = "sqlalchemy-spanner" %}
{% set version = "1.6.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # source from PyPI is missing version.py
  url: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: d246c841cc2db4aebb40e49d897e3f636eb2bf1dc3269b7f7b33c7f84612979c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=1.1.13
    - google-cloud-spanner >=3.12.0
    - alembic

test:
  imports:
    - google.cloud.sqlalchemy_spanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy
  summary: SQLAlchemy dialect integrated into Cloud Spanner database
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
