{% set name = "sqlalchemy-spanner" %}
{% set version = "1.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # source from PyPI is missing version.py
  url: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 8cad45ec90022db072f2d4cbcf2208de0a07ec0c2b012f77d3190e89b709ec8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - sqlalchemy >=1.1.13
    - google-cloud-spanner >=3.12.0
    - alembic

test:
  imports:
    - google.cloud.sqlalchemy_spanner
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy
  summary: SQLAlchemy dialect integrated into Cloud Spanner database
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
