{% set name = "sqlalchemy-spanner" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # source from PyPI is missing version.py
  url: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b3d6e2bfeed163e14667cefbedf922ce9a478def9f82b0c5c5b21febb6940e26

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - sqlalchemy >=1.1.13
    - google-cloud-spanner >=3.12.0
    - alembic

test:
  imports:
    - google.cloud.sqlalchemy_spanner
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cloudspannerecosystem/python-spanner-sqlalchemy
  summary: SQLAlchemy dialect integrated into Cloud Spanner database
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - xylar
    - hadim
